### ISSUE TITLE
Option to exclude files based on patterns

### ISSUE THREAD

**Issue by jeetsukumaran** [iiz00/obsidian-daily-note-outline#16]
Is there a way to modify the logic by which notes are picked up? I currently have other notes in the my daily notes folder (e.g, I have separate work cycle notes, etc.). I would like to exclude them from being seen completely.

**Comment by iiz00** [comment]
DNO does not use its own logic to extract daily/periodic notes, but uses the methods of the Periodic Notes plugin.
The internal behavior of the Periodic Notes plugin is very different between v0.0.17 and 1.0.0-beta3. (DNO behavior changes accordingly).
Beta3 seems to recognize a wider range of file names as periodic notes.
I am not considering using DNO's own logic, but it may be possible to add a setting to display only files that are more strict and follow a specified format.

Could you please elaborate more on the following?
- Are you using Periodic Notes v0.0.17 or v1.0.0-beta3? Or are you using only the core daily note plugin?
- Are you using only daily note or also weekly note, monthly note, etc.?
- Do you use multiple calendar sets?
- Can you give us some specific file names of files that you don't want displayed but are displayed?

**Comment by jeetsukumaran** [comment]
(1) I am using Periodic Notes 1.0.0-beta.3
(2) I am using daily / weekly/ monthly etc.
(3) I am using just one calender set.

Here is how I have got my daily notes set up:

```
logging/
  2023/
    daily/
    weekly/
    monthly/
```

with the Periodic Notes configuration as:

- Daily Note Format: `YYYY/[daily]/[log.]YYYY-MM-DD`
- Weekly Note Format: `YYYY/[weekly]/[log.]gggg-[W]WW`
- Monthly Note Format: `YYYY/[monthly]/[log.]YYYY-MM`

with all cases the folder set to "logging".

The problem is that I also have a "focus/work cycle" directory there, that logs work sessions. These are things I do NOT want to show up in the (wonderful!) daily note outline:

```
logging/
  2023/
    daily/
      log.2023-05-11
      log.2023-05-12
    monthly/
    sessions/
       log.session.2023-05-11.01
       log.session.2023-05-11.02
       log.session.2023-05-12.01
       log.session.2023-05-12.02
       log.session.foo
    weekly/
```

In the above example, "log.session.foo" does not show up, but "log.session.2023-05-12.01" does. So I think the PN plugin looks for any date-patterned file in the specified directory, whether or not it matches the specific pattern given in the filename template. To me, this heuristic seems a bit broad, but maybe it makes sense to allow people to be more relaxed with their naming conventions! Either way, it would be nice to exclude these from the listing.

Thank you for your consideration :)

**Comment by iiz00** [comment]
Please try turning on
`Settings -> others -> Show only exactly matched files`
in v1.2.0.
I hope this is the behavior you expect.

**Comment by jeetsukumaran** [comment]
This works wonderfully! Thank you!
