### ISSUE TITLE
[FR] Case Insensitive Extraction

### ISSUE THREAD

**Issue by jun6lee** [iiz00/obsidian-daily-note-outline#20]
On my daily journals for instance, sometimes I may start with a capitalised sentence.
In another, I might list out things I did in the day.

Currently extracting for "swim" and "Swim" give me different/limited results.
I do see the merit in this, but it being a Setting option to toggle would be a nice to-have.

Loving it otherwise. It's saved me creating an outline template. :)
Keep up the good work of making our lives easier.

**Comment by iiz00** [comment]
The case-sensitivity in extraction is indeed inconvenient (I usually write my daily notes in Japanese, so I had not noticed the inconvenience).
I think it is a rare situation that needs to be case-sensitive in the extraction function of this plugin, so I think I will make it case-insensitive in the extraction function.
It shouldn't be hard to fix, but please wait a bit until I have time.

**Comment by iiz00** [comment]
Please try v1.2.2.
If you have any problem, please let me know.

**Comment by jun6lee** [comment]
Perfect, thank you!
