### ISSUE TITLE
Failed to open

### ISSUE THREAD

**Issue by yoghurtdewdew** [iiz00/obsidian-daily-note-outline#25]
<img width="257" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/4df7844a-d3b4-43d7-b9f9-0fcdbaafe1f6">
Failed to open a daily note or a periodic note.

<img width="470" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/b4646d95-d17f-4f6c-b718-ebd53a1994e3">

Seemed to conflict with code block from Toggl Track plugin?

**Comment by iiz00** [comment]
The error messages appear to indicate that errors are occurring in four plugins: obsidian-togg.... .ntegration, todoist-text, fload-search, oblogger.
I am not sure what is going on and would appreciate more information.
- Is the problem still occurring when these four plugins are turned off?
- If so, please provide details on the problem you are experiencing. Is there something wrong with DNO's view? Or, if DNO and any of the 4 plugins are activated, does any of commands that should open daily note stop working?

**Comment by yoghurtdewdew** [comment]
Thanks for your reply! There may be something wrong with the code with one of the plugin, now the periodic notes could be opened!

But I could not found my daily notes, they are not shown in DNO's view, there is only week, month, quarter, and year in DNO's view.

**Comment by iiz00** [comment]
With the above 4 plugins turned off, in the DNO view, weekly notes, monthly notes, etc. are displayed, but daily notes are not displayed?
1. If you are using the beta version of Periodic Notes
, have you installed it using the obsidian BRAT plugin? If not, it may not work properly. (Please see https://github.com/iiz00/obsidian-daily-note-outline/issues/9)

2. Is Daily Note core plugin turned on? If so, are the settings of the Daily Note core plugin and the Periodic Notes plugin the same? Please turn off the Daily Note core plugin and try to match the settings of the Periodic Notes plugin with those of the Daily Note plugin.

If the above does not improve the situation, please let me know the following
- If you install and use PN and DNO in the Sandbox vault, does the problem reproduce?
- What errors do you see in the console if you turn off the above 4 plugins? Also do you get popup messages like in the first post?
- In DNO view, icons, weekly note, etc. are displayed and work, but the list is blank only when the granularity is 'day'?
- What is the format of the daily note filename?

**Comment by yoghurtdewdew** [comment]
I didn't close the plugins because I realized that I couldn't open it before, possibly because it would immediately render the code results related to those plugins when I click on a note/line in DNO, and when there was an error in the code in my weekly note, which caused the opening to fail. After modifying the code in my weekly note, I was able to open it.

I am using periodic notes plugin installed in plugin market (Will this be different from using brat to install the periodic notes plugin?), with daily note core plugin turned on. 

The settings were like: 
<img width="870" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/c31b0610-63c9-49e3-b60d-89f92d697dd1">

I clicked on **Migrate** button, then click on week/month/quarter/year on DNO’s view, but when I click on **year**, it didn't turn into week (before it did) nor anything and Obsidian comed into a grey view. Restart obsidian and tried twice in clicking on **year** and it comed into a grey view again.

<img width="1956" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/e2c8c7fc-23f2-4e0d-b096-fb8ae4525c35">

And if I disable the periodic notes in DNO options and even if I futher turned off periodic notes plugin, it showed no daily note
<img width="1246" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/24dc9199-10e7-4a48-bbb9-458b16950a47">
<img width="1257" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/5298520c-f8b2-4cbe-b463-19edcd3ae228">


I enable the periodic notes in DNO options, it showed year. If I click on **year**, it would come into a grey view.
<img width="1222" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/45de8068-08e6-4eb2-a2b6-e92352ccce01">

My setting in periodic notes plugin and daily note core plugin: they were the same.
<img width="720" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/492bde11-ac27-41cf-8cb2-0f39595134aa">
<img width="933" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/1a1eb6e8-f5e9-464d-bae0-bf6ada272a37">

And the list name of 'day' has never shown, not blank.

Well, there is good news!

Finally, I uninstalled and reinstalled DNO, it was normally showed daily and periodic notes! I even thought to reinstall obsidian, now I need not to do so.

Thank you for your great help! Love this cute plugin! You're really very creative to make this a awesome plugin!

**Comment by iiz00** [comment]
Glad to hear it! 😄  Also, thanks for the detailed information!

A few additional points:
- When DNO detects that Periodic Notes is activated, it uses the Periodic Notes settings, so if Daily Notes is turned off in PN settings as in your first screenshot, daily notes will not appear in the view. At the moment this is a specification.
- However, looking at your grayed-out screenshot, there may be a bug in the handling of certain combinations of settings (or, more likely, changing them) in DNO and PN. If I coulg find the conditions to reproduce it, I will fix it. Until then, please restart or reinstall.
- There are two versions of Periodic Notes in wide use: v0.0.17, which can be installed from the community plugin store, and v1.0.0-beta3, which can be installed by using BRAT plugin, etc. Switching between multiple calendar sets, etc. has been implemented in the beta version. The internal behavior has changed significantly between the two versions of PN, and internal behavior of DNO also changes depending on the PN version (the same can be said about possible errors 😅 ).

**Comment by yoghurtdewdew** [comment]
Thanks a lot for your detailed information! 😊
