### ISSUE TITLE
Support custom status of todos

### ISSUE THREAD

**Issue by yoghurtdewdew** [iiz00/obsidian-daily-note-outline#26]
![image](https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/0e40f6b9-2fb5-4474-9742-54d3e4adb1d6)
![image](https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/2b0c9e10-cd78-4ba0-9e66-e62e4a1afca4)

I use a lot of custom status of checkbox as I am using custom themes (mininal, things, …), maybe there could be a better way to show them in DNO.

For example, to show the character in the checkbox 😊

**Comment by iiz00** [comment]
You can display the text inside the checkboxes by turning on "Appearance" > "Tasks" > "Add checkbox text to prefix" in the settings screen. It might be better to hide the icons.
By the way, is there some official or de facto standard set of custom statuses? If you know of one, I would appreciate a link.

**Comment by yoghurtdewdew** [comment]
Thank you for your guidance. I have found the corresponding options, but I am thinking that if I could make the letters appear in the check box, it might be better to identify them.

I am not familiar with code, but I know some plugins would show some information, hope that would be useful:

obsidian://show-plugin?id=journal-review
<img width="298" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/899fb28d-db4c-4724-a8de-c1e6c81cf372">

obsidian://show-plugin?id=tasks-calendar-wrapper
<img width="275" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/63794438/9b4021e7-6474-4281-8ca2-17e131947ff3">

obsidian://show-plugin?id=time-ruler
There maybe were something wrong and it does not show tasks now. It simply showed the letter in the checkbox.

Theme:
https://github.com/kepano/obsidian-minimal
https://github.com/colineckert/obsidian-things
https://github.com/PKM-er/Blue-Topaz_Obsidian-css

I think the most basically used will be:
```
- [ ] to-do
- [/] incomplete
- [x] done
- [-] canceled
- [>] forwarded
- [<] scheduling
- [?] question
- [!] important
- [*] star
- ["] quote
- [l] location
- [b] bookmark
- [i] information
- [S] savings
- [I] idea
- [p] pros
- [c] cons
- [f] fire
- [k] key
- [w] win
- [u] up
- [d] down
```

**Comment by iiz00** [comment]
Thanks for the useful information.
I think Journal Review plugin may be rendering markdown.
DNO is simple icon + text; Obsidian uses the https://lucide.dev/ icon and DNO uses that too.
It's difficult to display the same as the editor, but it doesn't seem difficult to display some similar icons from the built-in icons.
Minimal theme's custom status might be a good reference. I will consider implementing it in a future update.

**Comment by yoghurtdewdew** [comment]
Got it! Thank you very much for your excellent development technique. Looking forward to this! :D

**Comment by iiz00** [comment]
Now task icons for custom statuses are displayed in v1.3.0.
Please edit data.json directly if you want to change/add icons for custom statuses.
