### ISSUE TITLE
Option not to automatically show on Obsidian start

### ISSUE THREAD

**Issue by eXperitur** [iiz00/obsidian-daily-note-outline#30]
Thanks for this great plugin, I'm really enjoying using it and it really helped simplify my workflows. 

My only issue so far is that the daily note outline is automatically shown when I start obsidian, and I have to change what's shown in the panel each time. 

Unless I'm missing out on a very obvious way to do this some other way, it would be great to have the option not to automatically show on startup in the settings. :)

**Comment by iiz00** [comment]
Thank you for using the plugin 😄 
You're right, that behavior is unnatural and inconvenient.
I have tried to fix it in v1.3.1. Please give it a try and let me know if you have any problems.

**Comment by eXperitur** [comment]
This is perfect, thank you so much - I've tried it and it's all good!  😃 👍 👍 👍
