### ISSUE TITLE
[FR] Ability to make the tooltip display wider

### ISSUE THREAD

**Issue by DJHL** [iiz00/obsidian-daily-note-outline#36]
I would like to request the ability to make the tooltip display wider to make it easy to quickly read large texts from past notes, when hovering over a header.

I think this would especially help with text that's indented several levels.

This is how it displays for me now:
![image](https://github.com/iiz00/obsidian-daily-note-outline/assets/4988825/3840de8e-1d27-4360-92ab-a14a24533d75)

**Comment by iiz00** [comment]
Thanks for the request, I am not sure if that is possible as I am using Obsidian functionality as is to create the tooltip, but I will implement it when I figure out how.

**Comment by iiz00** [comment]
CSS seemed to be able to handle this.
Please try v1.4.1.

**Comment by DJHL** [comment]
Thank you very much for your fast response and update.

Right now I can only test it on my iPad, because I am traveling abroad. It seems to work much better. Big improvement.

I can give you more feedback in a few weeks time after I regained access to my laptop.

**Comment by iiz00** [comment]
I will close this issue for now. Please let me know if any problems arise.
