### ISSUE TITLE
Issue with Links in Property Section

### ISSUE THREAD

**Issue by lacrimak3** [iiz00/obsidian-daily-note-outline#37]
I would like to express my gratitude for creating such an excellent plugin. It has greatly enhanced my workflow and I sincerely appreciate your efforts.

I have been using your plugin. However, I've come across an issue after updating to version 1.4.0

It appears that items within the property section remain visible, despite efforts to hide them. For example, links in the property section persistently appear even when I've configured the settings to hide them.

**Comment by iiz00** [comment]
Sorry for the inconvenience. I will add a setting to display links in properties in the next update.
If you are in a hurry, could you try to edit data.json in DNO?
- Open data.json in DNO folder in an editor (make a backup if necessary).
- Find the line `"showPropertyLinks": true,`.
- Rewrite `true' to `false' and save it.
- Restart Obsidian.
This should hide the property links.

**Comment by iiz00** [comment]
Added  `show links in properties` in the settings v1.4.1.

**Comment by lacrimak3** [comment]
Thank you for addressing the issue so quickly..
