### ISSUE TITLE
Can't exclude empty headers (# ) and if I try to exclude " " (space and then enter) then all headers disappear

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [iiz00/obsidian-daily-note-outline#38]
Hi,

I have an empty H1 in all my daily notes that its sole purpose is to be a summary of my day. It can get quite long. However, most days, I don't bother with it. I only populate it at the end of the week.

I've tried to exclude it from the pane but I couldn't do it.

I tried
```
```
(which is a plain newline)

I've tried
```
 
```
(which is space and then new line)

Thank you for the help

**Comment by iiz00** [comment]
Thank you for using DNO!
Hmmm, I hadn't considered empty headings...
I would like to avoid implementing a setting like "Hide empty headings" on the DNO side. It might cause other problems...
Possible alternatives are
- Remove empty H1, or create H1 only when filling them in
- Hide H1 in the DNO setting
- Fill in H1 with a symbol or string that indicates that it is not filled in, and hide the string with DNO's simple filter. If you don't want it to be conspicuous, you can use markdown symbols such as `****` to make it almost invisible, at least in Live Preview.

**Comment by SunnyAureliusRichard** [comment]
Great, thanks!
