### ISSUE TITLE
Include / Exclude Behaviour

### ISSUE THREAD

**Issue by MMoMM-org** [iiz00/obsidian-daily-note-outline#4]
Hi,
it would be nice if you could allow a default of include / exclude behaviour.

At the moment you include everything by default and you can exclude headers, tags etc.

I would rather exclude everything by default and then include only specific headers, tags etc.

Also I don't know if it already works but I can't exclude header by level, eg. # Excluded Header with all the ##, ###, etc headers below it.

**Comment by iiz00** [comment]
Thanks for your feedback.
As you pointed out, the current filter does not take into account the hierarchy of elements, it simply hides the element.
The function to include/exclude outline elements with subsequent sections was one of the features I wanted to add, so I will try to implement it. Please bear with me for a while!

**Comment by iiz00** [comment]
Implemented the include/exclude filter in v0.4.0.
Please try it out and let me know if you have any questions or problems!
