### ISSUE TITLE
Daily notes in multiple folders breaks the outline

### ISSUE THREAD

**Issue by Colin5000** [iiz00/obsidian-daily-note-outline#40]
My daily notes are not all in one folder, but instead are organised in a separate folder for each year; Daily/2020, Daily/2021, Daily/2022, Daily/2023, Daily/2024 etc.

The outline only works within a single folder. It breaks when I try to shift between January and the preceding December.

Can this be changed so the outline sees all files within the higher-level folder; "Daily"?

**Comment by iiz00** [comment]
Thanks for using the plugin!
By "breaks outline" do you mean that you cannot use the left and right arrow icons to move the display period across years?
If so, as far as I have tried at hand, I have been able to move folders by year without any problems.
Could you please provide the following information?
- If you mean that you cannot move across years, what is happening when you click on the arrow icon? No reaction? Does the view display disappear? Or something else? Does the console displayed by Ctrl+Shift+I show any errors?
- Do you have the Daily Note core plugin enabled?
	- If so, what do you specify for the date format and folder, respectively?
- Do you have the Periodic Notes plugin enabled? If so, what is the version?
	- If so, what do you specify for the date format and folder, respectively?
- Any other information that might help us reproduce the problem?

**Comment by Colin5000** [comment]
Thanks for your quick response!

When I try to move across years by clicking the arrow icon I get the following error:
<img width="338" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/20413931/5eef0709-f2ac-4417-a94b-64a363034e98">


The Daily Note core plugin IS installed. These are the settings:
<img width="916" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/20413931/6416ec00-6e48-4275-9ac8-30a384e46b9f">


The Periodic Notes plugin is NOT installed.


My Daily Notes are stored in the following folder structure:
<img width="120" alt="image" src="https://github.com/iiz00/obsidian-daily-note-outline/assets/20413931/b458c77f-569d-4ced-8d39-00b526e8a18b">

Hope this helps.

**Comment by iiz00** [comment]
I see, if you specify `Journal/2024` for new file location, only the notes in the folder will be treated as daily notes.
I think you can fix it by specifying `Journal` for New file location setting and `YYYY/YYYY-MM-DD-ddd` for Date format.
See also the `Automatic subfolders` section of the help page below.
https://help.obsidian.md/Plugins/Daily+notes

**Comment by Colin5000** [comment]
Thanks, that makes perfect sense, and I tried it and it worked.
