### ISSUE TITLE
open outline in tab, left sidebar, or right sidebar by default

### ISSUE THREAD

**Issue by lofti-lofi** [iiz00/obsidian-daily-note-outline#7]
enhancement: choose default behavior for opening the outline view. options: new tab, left sidebar, and right sidebar

**Comment by iiz00** [comment]
Thank you for your suggestion.
Displaying it in the left sidebar seems not difficult. I have to look into how to display it on a tab later.
Do you know of any community plugins that can be configured like this that I could refer to?

**Comment by lofti-lofi** [comment]
Hi! I'm aware that the Custom Frames plugin has this functionality. 
![image](https://user-images.githubusercontent.com/76537723/210110491-5f3d761c-1503-4370-b52b-204640a8547e.png)

**Comment by iiz00** [comment]
Sorry for the late reply, and thank you for the information!
I think I can implement this in the next update.

**Comment by iiz00** [comment]
Implemented in v0.5.0. Let me know if you have any problems with it working!
